- alias: "start HassOS"
  initial_state: true
  trigger:
    platform: event
    event_type: service_registered
    event_data:
      domain: nodered
      service: trigger
  action:
  - service: notify.mobile_app_sm_g570m
    data:
      message: 'Iniciou'
  - delay: '00:00:01'
  - service: input_boolean.turn_on
    data:
      entity_id:
        - input_boolean.ha_start

- alias: "set Themes - by caulecriativo.com"
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.themes
  action:
  - service: frontend.set_theme
    data_template:
      name: >
        {{ trigger.to_state.state }}


