
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


recorder: !include includes/recorder/recorder.yaml

homeassistant:
  customize: !include_dir_merge_named includes/customize/

dialogflow:

input_boolean: !include_dir_merge_named includes/input_boolean/
input_number: !include_dir_merge_named includes/input_number/
input_text: !include_dir_merge_named includes/input_text/
input_select: !include_dir_merge_named includes/input_select/
switch: !include_dir_merge_list includes/switch/
group: !include_dir_merge_named includes/groups/
script: !include_dir_merge_named includes/script/
automation: !include_dir_merge_list includes/automation/
utility_meter: !include_dir_merge_named includes/utility_meter/
sensor: !include_dir_merge_list includes/sensor/
binary_sensor: !include_dir_merge_list includes/binary_sensor/
intent_script: !include_dir_merge_named includes/intent_script/
shell_command: !include_dir_merge_named includes/shell_command/
device_tracker: !include_dir_merge_named includes/device_tracker/

frontend:
  themes: !include_dir_merge_named themes

lovelace: !include lovelace.yaml


### ##    ## ######## ########  ######   ########     ###  ######## ####  #######  ##    ##  ######  
 #  ###   ##    ##    ##       ##    ##  ##     ##   ## ##    ##     ##  ##     ## ###   ## ##    ## 
 #  ####  ##    ##    ##       ##        ##     ##  ##   ##   ##     ##  ##     ## ####  ## ##       
 #  ## ## ##    ##    ######   ##   #### ########  ##     ##  ##     ##  ##     ## ## ## ##  ######  
 #  ##  ####    ##    ##       ##    ##  ##   ##   #########  ##     ##  ##     ## ##  ####       ## 
 #  ##   ###    ##    ##       ##    ##  ##    ##  ##     ##  ##     ##  ##     ## ##   ### ##    ## 
### ##    ##    ##    ########  ######   ##     ## ##     ##  ##    ####  #######  ##    ##  ######  

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

spotcast:
  sp_dc: !secret spotify_rick_sp_dc
  sp_key: !secret spotify_rick_sp_key
  accounts:
    rick:
      sp_dc: !secret spotify_rick_sp_dc
      sp_key: !secret spotify_rick_sp_key
    evi:
      sp_dc: !secret spotify_evi_sp_dc
      sp_key: !secret spotify_evi_sp_key

unified_remote_mac:
  host: 192.168.1.37

# # unified_remote_pc:
# #   host: 192.168.0.56

ifttt:
  key: !secret ifttt_key

tts:
  - platform: google_translate

  - platform: watson_tts
    watson_apikey: !secret watson_apikey
    voice: pt-BR_IsabelaV3Voice

  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    text_type: ssml
    voice: Ricardo
    region_name: sa-east-1

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: true
  
samsungtv_smart:
  - host: 192.168.1.35
    app_list: '{"Netflix": "3201907018807/org.tizen.netflixapp", "Prime Video": "3201910019365/org.tizen.primevideo", "YouTube": "111299001912/9Ur5IzDKqV.TizenYouTube", "Plex": "111199000681/kIciSQlYEM.plex", "Spotify": "rJeHak5zRg.Spotify", "GloboPlay": "org.tizen.globoplayapp", "Disney+": "3201901017640/MCmYXNxgcu.DisneyPlus", "PlayPlus": "z1MNYaVwYO.PlayPlus", "Telecine": "Z07uHrNtXB.TelecinePlay"}'
    channel_list: '{"Globo": "4", "SBT": "5@TV", "Record": "10@TV", "Band": "15@TV"}'


