##     ## ########    ###    ########  ######## ########  
##     ## ##         ## ##   ##     ## ##       ##     ## 
##     ## ##        ##   ##  ##     ## ##       ##     ## 
######### ######   ##     ## ##     ## ######   ########  
##     ## ##       ######### ##     ## ##       ##   ##   
##     ## ##       ##     ## ##     ## ##       ##    ##  
##     ## ######## ##     ## ########  ######## ##     ## 

custom_header:
  compact_mode: true
  footer_mode: true
  kiosk_mode: false
  hide_header: false
  hide_unused: true
  hide_help: true
  hide_config: true
  default_tab_on_refresh: false
  indicator_top: true
  exceptions:

    - conditions:
        user: Izadora
      config:
        disable_sidebar: true
        hide_header: true


##        #######  ##     ## ######## ##          ###     ######  ######## 
##       ##     ## ##     ## ##       ##         ## ##   ##    ## ##       
##       ##     ## ##     ## ##       ##        ##   ##  ##       ##       
##       ##     ## ##     ## ######   ##       ##     ## ##       ######   
##       ##     ##  ##   ##  ##       ##       ######### ##       ##       
##       ##     ##   ## ##   ##       ##       ##     ## ##    ## ##       
########  #######     ###    ######## ######## ##     ##  ######  ######## 

title: Gactos Izadora
views:
  - !include includes/lovelace/views/view_iza.yaml
  - !include includes/lovelace/views/view_stats.yaml
  - !include includes/lovelace/views/view_tools.yaml
  - !include includes/lovelace/views/view_apto.yaml