#                                                                      
#   #####     ##    #####  #####  ######  #####   #  ######   ####  
#   #    #   #  #     #      #    #       #    #  #  #       #      
#   #####   #    #    #      #    #####   #    #  #  #####    ####  
#   #    #  ######    #      #    #       #####   #  #            # 
#   #    #  #    #    #      #    #       #   #   #  #       #    # 
#   #####   #    #    #      #    ######  #    #  #  ######   ####  
#                                                                    
#   O que foi usado?
#
#     Sensor Template - https://www.home-assistant.io/integrations/template/
#     Sensor MQTT - https://www.home-assistant.io/integrations/sensor.mqtt/
#


- platform: template
  sensors:

    battery_medula_phone:
      friendly_name: "Battery - Medula Phone"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.battery_medula_phone_level')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if is_state('sensor.battery_medula_phone_state', 'charging') %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery-charging-100
          {% elif battery_round > 0 %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            mdi:battery-charging-outline
          {% endif %}
        {% endif %}
        {% else %} 
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert-variant-outline
          {% endif %}
        {% endif %}
        {% endif %}
      value_template: >-
        {{states('sensor.battery_medula_phone_level')}}
      attribute_templates:
        Status: >-
          {{states('sensor.battery_medula_phone_state') | replace("discharging", "Descarregando") | replace("charging", "Carregando") | replace("full", "Carga completa")  }}

    battery_rick_phone:
      friendly_name: "Battery - Rick Phone"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.battery_rick_phone_level')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if is_state_attr('sensor.battery_rick_phone_level', 'battery_status', 'Charging') %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery-charging-100
          {% elif battery_round > 0 %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            mdi:battery-charging-outline
          {% endif %}
        {% endif %}
        {% else %} 
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert-variant-outline
          {% endif %}
        {% endif %}
        {% endif %}
      value_template: >-
        {{states('sensor.battery_rick_phone_level')}}
      attribute_templates:
        Status: >-
          {{ state_attr('sensor.battery_rick_phone_level', 'battery_status') | replace("NotCharging", "Descarregando") | replace("Charging", "Carregando") | replace("Charged", "Carga completa") }}

    battery_macbook_rick:
      friendly_name: "Battery - MacBook Rick"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.battery_macbook_rick_level')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if is_state('sensor.battery_macbook_rick_state', 'Charging') or is_state_attr('sensor.battery_macbook_rick_state', 'Power Source State', 'AC Power') %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery-charging-100
          {% elif battery_round > 0 %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            mdi:battery-charging-outline
          {% endif %}
        {% endif %}
        {% else %} 
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert-variant-outline
          {% endif %}
        {% endif %}
        {% endif %}
      value_template: >-
        {{states('sensor.battery_macbook_rick_level')}}
      attribute_templates:
        Status: >-
          {{ states('sensor.battery_macbook_rick_state') | replace("Not Charging", "Descarregando") | replace("Charging", "Carregando") | replace("Full", "Carga completa") }}


    battery_macbook_iza:
      friendly_name: "Battery - MacBook Iza"
      unit_of_measurement: '%'
      icon_template: >-
        {% set battery_level = states('sensor.battery_macbook_iza_level')|int('unknown') %}
        {% set battery_round = (battery_level|int / 10)|int * 10 %}
        {% if is_state('sensor.battery_macbook_iza_state', 'Charging') or is_state_attr('sensor.battery_macbook_iza_state', 'Power Source State', 'AC Power') %}
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery-charging-100
          {% elif battery_round > 0 %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            mdi:battery-charging-outline
          {% endif %}
        {% endif %}
        {% else %} 
        {% if battery_level == 'unknown' %}
          mdi:battery-unknown
        {% else %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert-variant-outline
          {% endif %}
        {% endif %}
        {% endif %}
      value_template: >-
        {{states('sensor.battery_macbook_iza_level')}}
      attribute_templates:
        Status: >-
          {{ states('sensor.battery_macbook_iza_state') | replace("Not Charging", "Descarregando") | replace("Charging", "Carregando") | replace("Full", "Carga completa") }}