#                                                                      
#   #####     ##    #####  #####  ######  #####   #  ######   ####  
#   #    #   #  #     #      #    #       #    #  #  #       #      
#   #####   #    #    #      #    #####   #    #  #  #####    ####  
#   #    #  ######    #      #    #       #####   #  #            # 
#   #    #  #    #    #      #    #       #   #   #  #       #    # 
#   #####   #    #    #      #    ######  #    #  #  ######   ####  
#                                                                    
#   O que foi usado?
#
#     Sensor Template - https://www.home-assistant.io/integrations/template/
#     Sensor MQTT - https://www.home-assistant.io/integrations/sensor.mqtt/
#


- platform: template
  sensors:

    battery_rick_phone:
      friendly_name: "Ciclo"
      unit_of_measurement: '%'
      icon_template: "{{state_attr('sensor.battery_rick_phone_state', 'icon')}}"
      value_template: >-
        {{states('sensor.battery_rick_phone_level')}}
      attribute_templates:
        Status: >-
          {{states('sensor.battery_rick_phone_state')}}


    # # Sensor para gerar um status mais amigável da bateria em português
    # battery_rick_phone_status:
    #   friendly_name: 'Battery - J5'
    #   icon_template: "{% if is_state('sensor.battery_rick_phone', '100') %} mdi:battery
    #   {% elif is_state_attr('sensor.battery_rick_phone', 'is_charging', false) %} mdi:battery-alert
    #   {% elif is_state_attr('sensor.battery_rick_phone', 'is_charging', true) %} mdi:battery-charging
    #   {% endif %}"
    #   value_template: "{% if is_state('sensor.battery_rick_phone', '100') %} Carregada
    #   {% elif is_state_attr('sensor.battery_rick_phone', 'is_charging', false) %} Descarregando
    #   {% elif is_state_attr('sensor.battery_rick_phone', 'is_charging', true) %} Carregando
    #   {% endif %}"

#     # Sensor para gerar um status mais amigável da bateria em português
#     battery_evi_phone_status:
#       friendly_name: 'Battery - Iphone'
#       icon_template: "{% if is_state_attr('sensor.battery_evi_phone', 'battery_status', 'Charging') %} mdi:battery-charging
#       {% elif is_state_attr('sensor.battery_evi_phone', 'battery_status', 'NotCharging') %} mdi:battery-alert
#       {% elif is_state_attr('sensor.battery_evi_phone', 'battery_status', 'Charged') %} mdi:battery
#       {% endif %}"
#       value_template: "{% if is_state_attr('sensor.battery_evi_phone', 'battery_status', 'Charging') %} Carregando
#       {% elif is_state_attr('sensor.battery_evi_phone', 'battery_status', 'NotCharging') %} Descarregando
#       {% elif is_state_attr('sensor.battery_evi_phone', 'battery_status', 'Charged') %} Carregada
#       {% endif %}"

#   # Sensor para coletar a bateria de um tablet que uso como dashboard
# - platform: mqtt
#   name: "Battery - Tab"
#   state_topic: "ha/sensor/android_tab_battery/attributes"
#   unit_of_measurement: '%'
#   value_template: "{{ value_json.state }}"
#   json_attributes_topic: "ha/sensor/android_tab_battery/attributes"